export const activos = [
    {
        id: 1,
        codigo: 'LAB-02',
        nombre: 'Computadora Laboratorio 02',
        categoria: 'Computadora',
        marca: 'TUF Gaming',
        modelo: '---',
        serie: '---',
        estado: 'Operativo',
        responsable: 'Evert L. Cuevas',
        departamento: 'Laboratorio',
        sucursal: 'Sucursal Central',
        ubicacion: 'Laboratorio',
        fechaAdquisicion: '15/01/2025',
    },
    {
        id: 2,
        codigo: 'ADM-03',
        nombre: 'Impresora Administración 03',
        categoria: 'Impresora',
        marca: 'HP',
        modelo: 'LaserJet Pro',
        serie: 'HPADM003',
        estado: 'En mantenimiento',
        responsable: 'María López',
        departamento: 'Administración',
        sucursal: 'Sucursal Central',
        ubicacion: 'Administración',
        fechaAdquisicion: '10/05/2024',
    },
    {
        id: 3,
        codigo: 'SEG-05',
        nombre: 'Cámara de seguridad 05',
        categoria: 'Cámara',
        marca: 'Hikvision',
        modelo: 'DS-2CD',
        serie: 'HKSEG005',
        estado: 'Operativo',
        responsable: 'Seguridad',
        departamento: 'Seguridad',
        sucursal: 'Sucursal Norte',
        ubicacion: 'Acceso principal',
        fechaAdquisicion: '22/03/2025',
    },
    {
        id: 4,
        codigo: 'RED-01',
        nombre: 'Switch principal',
        categoria: 'Equipo de red',
        marca: 'Cisco',
        modelo: 'CBS350',
        serie: 'CSRED001',
        estado: 'Operativo',
        responsable: 'Tecnología',
        departamento: 'Tecnología',
        sucursal: 'Sucursal Sur',
        ubicacion: 'Sala de comunicaciones',
        fechaAdquisicion: '08/02/2024',
    },
    {
        id: 5,
        codigo: 'LAB-08',
        nombre: 'Equipo biomédico LAB-08',
        categoria: 'Equipo biomédico',
        marca: 'Mindray',
        modelo: '---',
        serie: 'MBLAB008',
        estado: 'Operativo',
        responsable: 'Personal médico',
        departamento: 'Laboratorio',
        sucursal: 'Sucursal Central',
        ubicacion: 'Laboratorio',
        fechaAdquisicion: '18/07/2024',
    },
    {
        id: 6,
        codigo: 'TEC-014',
        nombre: 'Computadora Tecnología 14',
        categoria: 'Computadora',
        marca: 'Dell',
        modelo: 'OptiPlex 7090',
        serie: 'DELLTEC014',
        estado: 'Operativo',
        responsable: 'Carlos Pérez',
        departamento: 'Tecnología',
        sucursal: 'Sucursal Central',
        ubicacion: 'Oficina TI',
        fechaAdquisicion: '12/11/2023',
    },
    {
        id: 7,
        codigo: 'ADM-07',
        nombre: 'Impresora Administración 07',
        categoria: 'Impresora',
        marca: 'Brother',
        modelo: 'MFC-L8900',
        serie: 'BRADM007',
        estado: 'Fuera de servicio',
        responsable: 'Administración',
        departamento: 'Administración',
        sucursal: 'Sucursal Norte',
        ubicacion: 'Archivo',
        fechaAdquisicion: '03/09/2022',
    },
];

export const categoriasActivos = [
    'Computadora',
    'Equipo biomédico',
    'Cámara',
    'Impresora',
    'Equipo de red',
];

export const obtenerActivoPorId = (id) =>
    activos.find((activo) => activo.id === Number(id));