export const activos = [
    {
        id: 1,
        codigo: 'LAB-02',
        numeroInventarioContable: 'INV-2025-0001',
        nombre: 'Computadora Laboratorio 02',
        categoria: 'Computadora',
        fabricante: 'Dell',
        marca: 'TUF Gaming',
        modelo: '---',
        serie: 'DXL-001-2025',
        estado: 'Operativo',
        responsable: 'Evert L. Cuevas',
        departamento: 'Laboratorio',
        sucursal: 'Sucursal Central',
        ubicacion: 'Laboratorio',
        detalle: 'Equipo de cómputo para labores clínicas y preparación de datos.',
        observacion: 'Se realiza revisión mensual de hardware y software.',
        fechaAdquisicion: '15/01/2025',
    },
    {
        id: 2,
        codigo: 'ADM-03',
        numeroInventarioContable: 'INV-2024-0042',
        nombre: 'Impresora Administración 03',
        categoria: 'Impresora',
        fabricante: 'HP',
        marca: 'HP',
        modelo: 'LaserJet Pro',
        serie: 'HPADM003',
        estado: 'En mantenimiento',
        responsable: 'María López',
        departamento: 'Administración',
        sucursal: 'Sucursal Central',
        ubicacion: 'Administración',
        detalle: 'Impresora multifuncional utilizada para documentación administrativa.',
        observacion: 'Se requiere limpieza y reemplazo de cartucho de tóner.',
        fechaAdquisicion: '10/05/2024',
    },
    {
        id: 3,
        codigo: 'SEG-05',
        numeroInventarioContable: 'INV-2025-0018',
        nombre: 'Cámara de seguridad 05',
        categoria: 'Cámara',
        fabricante: 'Hikvision',
        marca: 'Hikvision',
        modelo: 'DS-2CD',
        serie: 'HKSEG005',
        estado: 'Operativo',
        responsable: 'Seguridad',
        departamento: 'Seguridad',
        sucursal: 'Sucursal Norte',
        ubicacion: 'Acceso principal',
        detalle: 'Cámara IP para video vigilancia de acceso vehicular y peatonal.',
        observacion: 'Conectada al sistema de seguridad central con respaldo diario.',
        fechaAdquisicion: '22/03/2025',
    },
    {
        id: 4,
        codigo: 'RED-01',
        numeroInventarioContable: 'INV-2024-0087',
        nombre: 'Switch principal',
        categoria: 'Equipo de red',
        fabricante: 'Cisco',
        marca: 'Cisco',
        modelo: 'CBS350',
        serie: 'CSRED001',
        estado: 'Operativo',
        responsable: 'Tecnología',
        departamento: 'Tecnología',
        sucursal: 'Sucursal Sur',
        ubicacion: 'Sala de comunicaciones',
        detalle: 'Switch de distribución principal para conectividad corporativa.',
        observacion: 'Se actualiza firmware cada 6 meses para asegurar estabilidad.',
        fechaAdquisicion: '08/02/2024',
    },
    {
        id: 5,
        codigo: 'LAB-08',
        numeroInventarioContable: 'INV-2024-0105',
        nombre: 'Equipo biomédico LAB-08',
        categoria: 'Equipo biomédico',
        fabricante: 'Mindray',
        marca: 'Mindray',
        modelo: '---',
        serie: 'MBLAB008',
        estado: 'Operativo',
        responsable: 'Personal médico',
        departamento: 'Laboratorio',
        sucursal: 'Sucursal Central',
        ubicacion: 'Laboratorio',
        detalle: 'Equipo biomédico para soporte clínico y análisis de laboratorio.',
        observacion: 'Se asigna con revisión de mantenimiento preventivo trimestral.',
        fechaAdquisicion: '18/07/2024',
    },
    {
        id: 6,
        codigo: 'TEC-014',
        numeroInventarioContable: 'INV-2023-0214',
        nombre: 'Computadora Tecnología 14',
        categoria: 'Computadora',
        fabricante: 'Dell',
        marca: 'Dell',
        modelo: 'OptiPlex 7090',
        serie: 'DELLTEC014',
        estado: 'Operativo',
        responsable: 'Carlos Pérez',
        departamento: 'Tecnología',
        sucursal: 'Sucursal Central',
        ubicacion: 'Oficina TI',
        detalle: 'Computadora de uso profesional para apoyo técnico y gestión de incidencias.',
        observacion: 'Se mantiene actualizada con licencias y parches de seguridad.',
        fechaAdquisicion: '12/11/2023',
    },
    {
        id: 7,
        codigo: 'ADM-07',
        numeroInventarioContable: 'INV-2022-0182',
        nombre: 'Impresora Administración 07',
        categoria: 'Impresora',
        fabricante: 'Brother',
        marca: 'Brother',
        modelo: 'MFC-L8900',
        serie: 'BRADM007',
        estado: 'Fuera de servicio',
        responsable: 'Administración',
        departamento: 'Administración',
        sucursal: 'Sucursal Norte',
        ubicacion: 'Archivo',
        detalle: 'Impresora multifuncional para procesos administrativos, facturación y correspondencia.',
        observacion: 'Actualmente en espera de revisión técnica y reemplazo de unidad de impresión.',
        fechaAdquisicion: '03/09/2022',
    },
];

export const categoriasActivos = [
    'Computadora',
    'Equipo biomédico',
    'Cámara',
    'Impresora',
    'Equipo de red',
];

export const obtenerActivoPorId = (id) =>
    activos.find((activo) => activo.id === Number(id));