export const mantenimientos = [
    {
        id: 1001,
        activo: 'Computadora LAB-02',
        codigo: 'LAB-02',
        tipo: 'Preventivo',
        categoria: 'Computadora',
        fechaProgramada: '30/09/2026',
        fechaUltimo: '30/06/2026',
        proximaFecha: '30/12/2026',
        tecnico: 'Carlos Pérez',
        estado: 'Programado',
        prioridad: 'Media',
        sucursal: 'Sucursal Central',
    },
    {
        id: 1002,
        activo: 'Impresora ADM-03',
        codigo: 'ADM-03',
        tipo: 'Correctivo',
        categoria: 'Impresora',
        fechaProgramada: '28/09/2026',
        fechaUltimo: '20/08/2026',
        proximaFecha: '-',
        tecnico: 'Ana Rodríguez',
        estado: 'En curso',
        prioridad: 'Alta',
        sucursal: 'Sucursal Central',
    },
    {
        id: 1003,
        activo: 'Cámara SEG-05',
        codigo: 'SEG-05',
        tipo: 'Preventivo',
        categoria: 'Cámara',
        fechaProgramada: '02/10/2026',
        fechaUltimo: '02/07/2026',
        proximaFecha: '02/01/2027',
        tecnico: 'Pedro Vargas',
        estado: 'Programado',
        prioridad: 'Baja',
        sucursal: 'Sucursal Norte',
    },
    {
        id: 1004,
        activo: 'Equipo de red RED-01',
        codigo: 'RED-01',
        tipo: 'Correctivo',
        categoria: 'Red',
        fechaProgramada: '27/09/2026',
        fechaUltimo: '-',
        proximaFecha: '-',
        tecnico: 'Carlos Pérez',
        estado: 'Completado',
        prioridad: 'Alta',
        sucursal: 'Sucursal Sur',
    },
    {
        id: 1005,
        activo: 'Equipo biomédico LAB-08',
        codigo: 'LAB-08',
        tipo: 'Preventivo',
        categoria: 'Equipo biomédico',
        fechaProgramada: '05/10/2026',
        fechaUltimo: '05/07/2026',
        proximaFecha: '05/01/2027',
        tecnico: 'Ana Rodríguez',
        estado: 'Programado',
        prioridad: 'Media',
        sucursal: 'Sucursal Central',
    },
];

export const obtenerMantenimientoPorId = (id) => {
    return mantenimientos.find(
        (mantenimiento) =>
            mantenimiento.id === Number(id)
    );
};