export const usuarios = [
    {
        id: 1,
        nombre: 'Evert Cuevas',
        username: 'admin',
        email: 'evert.cuevas@soporte.local',
        rol: 'Administrador',
        area: 'Tecnología',
        sucursal: 'Sucursal Central',
        estado: 'Activo',
        telefono: '+52 55 1234 5678',
    },
    {
        id: 2,
        nombre: 'Carlos Pérez',
        username: 'carlos.perez',
        email: 'carlos.perez@soporte.local',
        rol: 'Técnico de hardware',
        area: 'Soporte técnico',
        sucursal: 'Sucursal Central',
        estado: 'Activo',
        telefono: '+52 55 2345 6789',
    },
    {
        id: 3,
        nombre: 'Ana Rodríguez',
        username: 'ana.rodriguez',
        email: 'ana.rodriguez@soporte.local',
        rol: 'Especialista en red',
        area: 'Infraestructura',
        sucursal: 'Sucursal Norte',
        estado: 'Activo',
        telefono: '+52 55 3456 7890',
    },
    {
        id: 4,
        nombre: 'Pedro Vargas',
        username: 'pedro.vargas',
        email: 'pedro.vargas@soporte.local',
        rol: 'Técnico de cámaras',
        area: 'Seguridad',
        sucursal: 'Sucursal Sur',
        estado: 'En descanso',
        telefono: '+52 55 4567 8901',
    },
    {
        id: 5,
        nombre: 'María López',
        username: 'maria.lopez',
        email: 'maria.lopez@soporte.local',
        rol: 'Coordinadora de operaciones',
        area: 'Administración',
        sucursal: 'Sucursal Central',
        estado: 'Activo',
        telefono: '+52 55 5678 9012',
    },
];

export const obtenerUsuarioPorId = (id) =>
    usuarios.find((usuario) => usuario.id === Number(id));
